language: clojure
lein: 2.7.1
before_script:
  - sudo apt-get install python3
  - mkdir -p target
  - git clone http://github.com/plandes/zenbuild
install:
  - pip3 install -r src/python/requirements.txt
script: PYTHON_BIN=python3 ZBHOME=zenbuild make checkdep test inttest
jdk:
  - oraclejdk8
