language: clojure
lein: 2.7.1
dist: "trusty" 
#python: '3.6'
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
before_script:
  - mkdir -p target
  - git clone http://github.com/plandes/zenbuild
before_install:
  - sudo pip3 install -r src/python/requirements.txt
script: PYTHON_BIN=python3 ZBHOME=zenbuild make checkdep test inttest
jdk:
  - oraclejdk8
