language: clojure
lein: 2.7.1
#dist: "trusty" 
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
before_script:
  - sudo pip install -r src/python/requirements.txt
  - mkdir -p target
  - git clone http://github.com/plandes/zenbuild
script: PYTHON_BIN=python3 ZBHOME=zenbuild make checkdep test inttest
jdk:
  - oraclejdk8
