language: clojure
lein: 2.7.1
dist: "trusty" 
#python: '3.6'
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
before_script:
  - source ~/virtualenv/python3.5/bin/activate
  - mkdir -p target
  - git clone http://github.com/plandes/zenbuild
before_install:
  - pip3 install -r src/python/requirements.txt
script: ZBHOME=zenbuild make checkdep test inttest
jdk:
  - oraclejdk8
