language: clojure
lein: 2.7.1
python:
  - "3.6"
  - "pypy3"
before_script:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
  - mkdir -p target
  - git clone http://github.com/plandes/zenbuild
install:
  - pip3 install -r src/python/requirements.txt
script: ZBHOME=zenbuild make checkdep test inttest
jdk:
  - oraclejdk8
