language: clojure
lein: 2.7.1
python:
  - "3.6"
before_script:
  - mkdir -p target
  - git clone http://github.com/plandes/zenbuild
script: ZBHOME=zenbuild make checkdep test pydeps inttest
jdk:
  - oraclejdk8
